// Tests for module packs: `faraday pack list` + `faraday pack add`. Uses a real
// tmpdir lesson generated by the scaffold pipeline, no install.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { generateLesson } from "./generate.mjs";
import { listPacks, installPack } from "./pack.mjs";

async function tmp() {
  return fs.mkdtemp(path.join(os.tmpdir(), "faraday-pack-test-"));
}
const read = (dir, rel) => fs.readFile(path.join(dir, rel), "utf8");
const exists = async (p) => !!(await fs.stat(p).catch(() => null));

test("listPacks includes all shipped packs", async () => {
  const packs = await listPacks();
  const names = packs.map((p) => p.name);
  for (const n of ["three", "tutor", "srs", "lecture-design"]) {
    assert.ok(names.includes(n), `expected a \`${n}\` pack`);
  }
  const three = packs.find((p) => p.name === "three");
  assert.ok(three.runtime?.dependencies?.["@faraday-academy/three"], "three pins its runtime pkg");
  assert.ok(three.runtime?.variants?.physics, "three exposes a physics variant");
  assert.ok(three.skill?.reference, "three ships a skill reference");
});

async function scaffold(name) {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name, uuid: () => "fixed-id" });
  return target;
}

test("installPack(tutor) drops the durable server + wiring", async () => {
  const target = await scaffold("Tutor Host");
  await installPack("tutor", { fromDir: target });

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.equal(pkg.dependencies["@faraday-academy/tutor"], "0.1.0");
  for (const dep of ["ai", "@ai-sdk/workflow", "workflow", "nitro", "zod"]) {
    assert.ok(pkg.dependencies[dep], `server dep ${dep} missing`);
  }
  assert.ok(await exists(path.join(target, "api/chat.post.ts")), "nitro route copied");
  assert.ok(await exists(path.join(target, "workflows/tutor-agent.ts")), "workflow agent copied");
  assert.ok(await exists(path.join(target, "docs/tutor.md")), "tutor guide copied");
  assert.match(await read(target, "vite.config.ts"), /nitro|workflow/);
  assert.match(await read(target, "pnpm-workspace.yaml"), /nodeLinker:\s*hoisted/);
  assert.match(await read(target, "src/app.css"), /@faraday-academy\/tutor\/styles\.css/);
  assert.ok(await exists(path.join(target, ".faraday/packs/tutor/pack.md")), "skill installed");
});

test("installPack(srs) copies the author-editable component, no new npm deps", async () => {
  const target = await scaffold("SRS Host");
  const before = JSON.parse(await read(target, "package.json"));
  await installPack("srs", { fromDir: target });

  assert.ok(await exists(path.join(target, "src/lesson/srs/Flashcards.tsx")), "component copied");
  assert.ok(await exists(path.join(target, "src/lesson/srs/scheduler.ts")), "scheduler copied");
  assert.ok(await exists(path.join(target, ".faraday/packs/srs/pack.md")), "skill installed");

  const after = JSON.parse(await read(target, "package.json"));
  assert.deepEqual(after.dependencies, before.dependencies, "srs adds no runtime deps");
});

test("installPack(lecture-design) installs a skill FOLDER, no runtime", async () => {
  const target = await scaffold("Pedagogy Host");
  const result = await installPack("lecture-design", { fromDir: target });

  // skill reference is a directory -> the whole folder is installed
  for (const f of ["overview.md", "spaced-retrieval.md", "methods.md"]) {
    assert.ok(await exists(path.join(target, ".faraday/packs/lecture-design", f)), `${f} installed`);
  }
  assert.equal(result.addedDeps.length, 0, "skill-only pack adds no deps");
  const agents = await read(target, "AGENTS.md");
  assert.ok(agents.includes("Pack `lecture-design`:"), "AGENTS.md pointer added");
});

test("installPack(three) wires the runtime half AND the skill half", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host", uuid: () => "fixed-id" });

  const result = await installPack("three", { fromDir: target });
  assert.equal(result.lessonRoot, target);

  // runtime half: deps pinned + sorted
  const pkg = JSON.parse(await read(target, "package.json"));
  assert.equal(pkg.dependencies["@faraday-academy/three"], "0.1.0");
  assert.ok(pkg.dependencies["@react-three/fiber"]);
  assert.ok(pkg.devDependencies["@types/three"]);
  const keys = Object.keys(pkg.dependencies);
  assert.deepEqual(keys, [...keys].sort((a, b) => a.localeCompare(b)), "deps stay sorted");

  // runtime half: css import injected
  const css = await read(target, "src/app.css");
  assert.ok(css.includes('@import "@faraday-academy/three/styles.css";'), "three css wired");

  // runtime half: examples copied
  assert.ok(await exists(path.join(target, "docs/examples/curriculum3d.tsx")), "example copied");

  // skill half: reference installed + pointer in AGENTS.md
  assert.ok(await exists(path.join(target, ".faraday/packs/three/pack.md")), "skill ref installed");
  const agents = await read(target, "AGENTS.md");
  assert.ok(agents.includes("Pack `three`:"), "AGENTS.md pointer added");

  // provenance records the pack
  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.ok(prov.packs.includes("three"), "provenance records the pack");
});

test("installPack is idempotent + supports the physics variant", async () => {
  const base = await tmp();
  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host 2", uuid: () => "fixed-id" });

  await installPack("three", { fromDir: target, variant: "physics" });
  await installPack("three", { fromDir: target, variant: "physics" }); // twice = no dupes

  const pkg = JSON.parse(await read(target, "package.json"));
  assert.ok(pkg.dependencies["@react-three/rapier"], "physics variant dep pinned");

  const css = await read(target, "src/app.css");
  const occurrences = css.split('@import "@faraday-academy/three/styles.css";').length - 1;
  assert.equal(occurrences, 1, "css import not duplicated on re-run");

  const agents = await read(target, "AGENTS.md");
  const pointers = agents.split("Pack `three`:").length - 1;
  assert.equal(pointers, 1, "AGENTS.md pointer not duplicated on re-run");

  const prov = JSON.parse(await read(target, ".faraday/provenance.json"));
  assert.equal(prov.packs.filter((p) => p === "three:physics").length, 1, "provenance not duplicated");
});

test("installPack rejects an unknown pack, a lesson-less dir, and a bad variant", async () => {
  const base = await tmp();
  // unknown pack fails at manifest read, before the lesson lookup
  await assert.rejects(() => installPack("nope", { fromDir: base }), /Unknown pack: nope/);
  // a dir with no lesson above it
  await assert.rejects(() => installPack("three", { fromDir: base }), /not inside a Faraday lesson/);

  const target = path.join(base, "lesson");
  await generateLesson({ targetDir: target, name: "Pack Host 3", uuid: () => "fixed-id" });
  await assert.rejects(() => installPack("three", { fromDir: target, variant: "nonsense" }), /no variant/);
});
